import {cp,mkdir,rm,access} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url)),output=path.join(root,'layero-dist');
if(path.relative(root,output)!=='layero-dist')throw new Error('Unsafe output directory');
await rm(output,{recursive:true,force:true});
await mkdir(output,{recursive:true});
await cp(path.join(root,'public'),output,{recursive:true,filter:file=>path.basename(file)!=='admin.html'});
await Promise.all(['index.html','site.js','admin.js','assets/logo.svg'].map(file=>access(path.join(output,file))));
console.log('Layero ready: Node server, protected editor and private S3 storage.');
